// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdxZB9bb8YZxtkDMew9dMgiIA0PZ341cU',
    appId: '1:492081025164:web:8126efda36f725a0bdeba9',
    messagingSenderId: '492081025164',
    projectId: 'ershad-38c61',
    authDomain: 'ershad-38c61.firebaseapp.com',
    storageBucket: 'ershad-38c61.firebasestorage.app',
    measurementId: 'G-Q28311KBTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKhL5mJU9r2bwGs-87l2P4DiLEy0vCyLM',
    appId: '1:492081025164:android:e53d2b21f804d85abdeba9',
    messagingSenderId: '492081025164',
    projectId: 'ershad-38c61',
    storageBucket: 'ershad-38c61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS1zRQ368ox2YZErSlHKbcoSgRlub-MoI',
    appId: '1:492081025164:ios:90309dd1d4ac7694bdeba9',
    messagingSenderId: '492081025164',
    projectId: 'ershad-38c61',
    storageBucket: 'ershad-38c61.firebasestorage.app',
    iosBundleId: 'com.example.acdemy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS1zRQ368ox2YZErSlHKbcoSgRlub-MoI',
    appId: '1:492081025164:ios:90309dd1d4ac7694bdeba9',
    messagingSenderId: '492081025164',
    projectId: 'ershad-38c61',
    storageBucket: 'ershad-38c61.firebasestorage.app',
    iosBundleId: 'com.example.acdemy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdxZB9bb8YZxtkDMew9dMgiIA0PZ341cU',
    appId: '1:492081025164:web:b25543e9363e11debdeba9',
    messagingSenderId: '492081025164',
    projectId: 'ershad-38c61',
    authDomain: 'ershad-38c61.firebaseapp.com',
    storageBucket: 'ershad-38c61.firebasestorage.app',
    measurementId: 'G-YKHM5QCZT3',
  );
}
